package com.batchfee.student.ui.fees

import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.core.content.FileProvider
import com.batchfee.student.data.firebase.StudentFirestoreRepository
import com.batchfee.student.data.models.*
import com.batchfee.student.domain.SessionManager
import com.batchfee.student.ui.theme.*
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.*

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ReceiptViewScreen(receiptId: String, onBack: () -> Unit) {
    val studentId by SessionManager.currentStudentId.collectAsState()
    val instituteId by SessionManager.currentInstituteId.collectAsState()
    val repo = remember { StudentFirestoreRepository() }
    val context = LocalContext.current
    val scope = rememberCoroutineScope()

    var receipt by remember { mutableStateOf<Receipt?>(null) }
    var student by remember { mutableStateOf<Student?>(null) }
    var institute by remember { mutableStateOf<Institute?>(null) }
    var isLoading by remember { mutableStateOf(true) }
    var pdfGenerated by remember { mutableStateOf(false) }
    var pdfFile by remember { mutableStateOf<File?>(null) }

    LaunchedEffect(receiptId, studentId, instituteId) {
        val sid = studentId ?: return@LaunchedEffect
        val iid = instituteId ?: return@LaunchedEffect
        try {
            val receipts = repo.getReceipts(iid, sid)
            receipt = receipts.find { it.id == receiptId }
            student = repo.getStudent(iid, sid)
            institute = repo.getInstitute(iid)
        } catch (_: Exception) { }
        isLoading = false
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Payment Receipt", fontWeight = FontWeight.Bold) },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.Filled.ArrowBack, null)
                    }
                },
                actions = {
                    if (pdfGenerated && pdfFile != null) {
                        IconButton(onClick = { sharePdf(context, pdfFile!!) }) {
                            Icon(Icons.Filled.Share, "Share")
                        }
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = MaterialTheme.colorScheme.surface
                )
            )
        }
    ) { padding ->
        if (isLoading) {
            Box(Modifier.fillMaxSize().padding(padding), contentAlignment = Alignment.Center) {
                CircularProgressIndicator(color = PrimaryBlue, strokeWidth = 3.dp)
            }
        } else if (receipt == null) {
            Box(Modifier.fillMaxSize().padding(padding), contentAlignment = Alignment.Center) {
                Text("Receipt not found", color = TextSecondaryLight)
            }
        } else {
            val r = receipt!!
            val s = student
            val inst = institute

            Column(
                modifier = Modifier
                    .fillMaxSize()
                    .padding(padding)
                    .verticalScroll(rememberScrollState())
                    .padding(16.dp)
            ) {
                // ════════════════════════════════════
                // RECEIPT CARD — Premium Design
                // ════════════════════════════════════
                Card(
                    modifier = Modifier.fillMaxWidth(),
                    shape = RoundedCornerShape(24.dp),
                    elevation = CardDefaults.cardElevation(defaultElevation = 6.dp),
                    colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface)
                ) {
                    Column(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(0.dp)
                    ) {
                        // Receipt Header
                        Box(
                            modifier = Modifier
                                .fillMaxWidth()
                                .background(
                                    Brush.linearGradient(
                                        colors = listOf(PrimaryBlue, Color(0xFF3730A3)),
                                        start = Offset.Zero, end = Offset(400f, 0f)
                                    ),
                                    RoundedCornerShape(topStart = 24.dp, topEnd = 24.dp)
                                )
                                .padding(24.dp),
                            contentAlignment = Alignment.Center
                        ) {
                            Column(horizontalAlignment = Alignment.CenterHorizontally) {
                                Text("PAYMENT RECEIPT",
                                    color = Color.White.copy(alpha = 0.8f), fontSize = 12.sp,
                                    letterSpacing = 3.sp, fontWeight = FontWeight.Medium)
                                Spacer(Modifier.height(4.dp))
                                Text(r.receiptNumber,
                                    color = Color.White, fontWeight = FontWeight.Bold, fontSize = 22.sp)
                            }
                        }

                        // Institute Info
                        Column(
                            modifier = Modifier.padding(20.dp),
                            horizontalAlignment = Alignment.CenterHorizontally
                        ) {
                            Text(inst?.name ?: "Institute",
                                fontWeight = FontWeight.Bold, fontSize = 18.sp)
                            if (inst?.address != null) {
                                Text(inst.address,
                                    color = TextSecondaryLight, fontSize = 12.sp,
                                    textAlign = TextAlign.Center)
                            }

                            Spacer(Modifier.height(16.dp))
                            HorizontalDivider()
                            Spacer(Modifier.height(16.dp))

                            // Details
                            ReceiptDetailRow("Receipt No", r.receiptNumber)
                            ReceiptDetailRow("Date",
                                SimpleDateFormat("dd MMMM yyyy", Locale.getDefault()).format(Date(r.receiptDateMs)))
                            if (s != null) {
                                ReceiptDetailRow("Student", "${s.fullName} (${s.studentCode})")
                            }
                            ReceiptDetailRow("Payment Method",
                                r.paymentMethod.replaceFirstChar { it.uppercase() })

                            Spacer(Modifier.height(16.dp))
                            HorizontalDivider()
                            Spacer(Modifier.height(16.dp))

                            // Amounts
                            ReceiptAmountRow("Total Amount", "\u09F3${String.format("%,.0f", r.totalAmount)}",
                                MaterialTheme.colorScheme.onSurface)
                            ReceiptAmountRow("Paid Amount", "\u09F3${String.format("%,.0f", r.paidAmount)}",
                                Color(0xFF10B981))
                            if (r.dueAmount > 0) {
                                ReceiptAmountRow("Due Amount", "\u09F3${String.format("%,.0f", r.dueAmount)}",
                                    Color(0xFFEF4444))
                            }

                            if (r.receiptText != null) {
                                Spacer(Modifier.height(16.dp))
                                HorizontalDivider()
                                Spacer(Modifier.height(12.dp))
                                Surface(
                                    shape = RoundedCornerShape(10.dp),
                                    color = Color(0xFFF8FAFC)
                                ) {
                                    Text(r.receiptText,
                                        modifier = Modifier.padding(12.dp),
                                        fontSize = 12.sp, color = TextSecondaryLight,
                                        textAlign = TextAlign.Center)
                                }
                            }

                            // Footer
                            Spacer(Modifier.height(20.dp))
                            HorizontalDivider()
                            Spacer(Modifier.height(12.dp))
                            Text("Thank you for your payment!",
                                fontSize = 12.sp, color = TextSecondaryLight.copy(alpha = 0.6f))
                        }
                    }
                }

                Spacer(Modifier.height(20.dp))

                // ════════════════════════════════════
                // ACTIONS
                // ════════════════════════════════════
                Button(
                    onClick = {
                        scope.launch {
                            val file = withContext(Dispatchers.IO) {
                                generateReceiptPdf(context, r, s, inst)
                            }
                            pdfFile = file
                            pdfGenerated = true
                        }
                    },
                    modifier = Modifier.fillMaxWidth().height(54.dp),
                    shape = RoundedCornerShape(16.dp),
                    colors = ButtonDefaults.buttonColors(containerColor = PrimaryBlue)
                ) {
                    Icon(Icons.Filled.Download, null, modifier = Modifier.size(20.dp))
                    Spacer(Modifier.width(8.dp))
                    Text("Download PDF", fontWeight = FontWeight.Bold, fontSize = 15.sp)
                }

                if (pdfGenerated && pdfFile != null) {
                    Spacer(Modifier.height(10.dp))
                    OutlinedButton(
                        onClick = { sharePdf(context, pdfFile!!) },
                        modifier = Modifier.fillMaxWidth().height(54.dp),
                        shape = RoundedCornerShape(16.dp)
                    ) {
                        Icon(Icons.Filled.Share, null, modifier = Modifier.size(20.dp))
                        Spacer(Modifier.width(8.dp))
                        Text("Share Receipt", fontWeight = FontWeight.Bold, fontSize = 15.sp)
                    }
                }

                Spacer(Modifier.height(32.dp))
            }
        }
    }
}

@Composable
private fun ReceiptDetailRow(label: String, value: String) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .padding(vertical = 4.dp),
        horizontalArrangement = Arrangement.SpaceBetween
    ) {
        Text(label, color = TextSecondaryLight, fontSize = 13.sp)
        Text(value, fontWeight = FontWeight.Medium, fontSize = 13.sp)
    }
}

@Composable
private fun ReceiptAmountRow(label: String, value: String, color: Color) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .padding(vertical = 4.dp),
        horizontalArrangement = Arrangement.SpaceBetween,
        verticalAlignment = Alignment.CenterVertically
    ) {
        Text(label, color = TextSecondaryLight, fontSize = 13.sp)
        Text(value, fontWeight = FontWeight.Bold, fontSize = 18.sp, color = color)
    }
}

// ── PDF Generation ──
private fun generateReceiptPdf(
    context: Context,
    receipt: Receipt,
    student: Student?,
    institute: Institute?
): File {
    val document = PdfDocument()
    val pageInfo = PdfDocument.PageInfo.Builder(280, 500, 1).create()
    val page = document.startPage(pageInfo)
    val canvas: Canvas = page.canvas

    val titlePaint = Paint().apply {
        textSize = 18f; isFakeBoldText = true; textAlign = Paint.Align.CENTER
    }
    val headerPaint = Paint().apply {
        textSize = 14f; isFakeBoldText = true; textAlign = Paint.Align.CENTER
    }
    val normalPaint = Paint().apply { textSize = 10f }
    val boldPaint = Paint().apply { textSize = 10f; typeface = Typeface.DEFAULT_BOLD }
    val smallPaint = Paint().apply { textSize = 8f }
    val linePaint = Paint().apply { strokeWidth = 1f }
    val greenPaint = Paint().apply {
        textSize = 14f; isFakeBoldText = true; textAlign = Paint.Align.RIGHT
        color = android.graphics.Color.parseColor("#059669")
    }
    val redPaint = Paint().apply {
        textSize = 12f; textAlign = Paint.Align.RIGHT
        color = android.graphics.Color.parseColor("#DC2626")
    }

    var y = 30f
    canvas.drawText(institute?.name ?: "Institute", 140f, y, titlePaint)
    y += 20f
    if (institute?.address != null) {
        canvas.drawText(institute.address!!, 140f, y, smallPaint)
        y += 15f
    }
    y += 10f
    canvas.drawLine(20f, y, 260f, y, linePaint)
    y += 15f
    canvas.drawText("PAYMENT RECEIPT", 140f, y, headerPaint)
    y += 15f
    canvas.drawText(receipt.receiptNumber, 140f, y, Paint().apply {
        textSize = 16f; isFakeBoldText = true; textAlign = Paint.Align.CENTER
    })
    y += 25f

    canvas.drawText("Date:", 25f, y, boldPaint)
    canvas.drawText(
        SimpleDateFormat("dd MMM yyyy", Locale.getDefault()).format(Date(receipt.receiptDateMs)),
        160f, y, normalPaint
    )
    y += 15f
    if (student != null) {
        canvas.drawText("Student:", 25f, y, boldPaint)
        canvas.drawText("${student.fullName} (${student.studentCode})", 160f, y, normalPaint)
        y += 15f
    }
    canvas.drawText("Method:", 25f, y, boldPaint)
    canvas.drawText(receipt.paymentMethod.replaceFirstChar { it.uppercase() }, 160f, y, normalPaint)
    y += 20f
    canvas.drawLine(20f, y, 260f, y, linePaint)
    y += 15f

    canvas.drawText("Total:", 25f, y, normalPaint)
    canvas.drawText("\u09F3${String.format("%.0f", receipt.totalAmount)}", 250f, y, normalPaint.apply { textAlign = Paint.Align.RIGHT })
    y += 18f
    canvas.drawText("Paid:", 25f, y, greenPaint.apply { textAlign = Paint.Align.LEFT })
    canvas.drawText("\u09F3${String.format("%.0f", receipt.paidAmount)}", 250f, y, greenPaint.apply { textAlign = Paint.Align.RIGHT })
    y += 18f
    if (receipt.dueAmount > 0) {
        canvas.drawText("Due:", 25f, y, redPaint.apply { textAlign = Paint.Align.LEFT })
        canvas.drawText("\u09F3${String.format("%.0f", receipt.dueAmount)}", 250f, y, redPaint)
        y += 18f
    }
    y += 10f
    canvas.drawLine(20f, y, 260f, y, linePaint)
    y += 15f
    if (receipt.receiptText != null) {
        canvas.drawText(receipt.receiptText!!, 140f, y, Paint().apply {
            textSize = 9f; textAlign = Paint.Align.CENTER
        })
    }

    document.finishPage(page)

    val dir = File(context.cacheDir, "pdfs")
    dir.mkdirs()
    val file = File(dir, "receipt_${receipt.receiptNumber}.pdf")
    FileOutputStream(file).use { out -> document.writeTo(out) }
    document.close()
    return file
}

private fun sharePdf(context: Context, file: File) {
    val uri = FileProvider.getUriForFile(
        context, "${context.packageName}.fileprovider", file
    )
    val shareIntent = Intent(Intent.ACTION_SEND).apply {
        type = "application/pdf"
        putExtra(Intent.EXTRA_STREAM, uri)
        addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
    }
    context.startActivity(Intent.createChooser(shareIntent, "Share Receipt"))
}
